name: Trigger auto deployment for autotrader and relay

on:
  push:
    branches: [dev]
    paths:
      - "**"
      - ".github/workflows/autotrader-AutoDeployTrigger-44d254ef-86c3-4f1e-ac6e-38003dbc16d7.yml"
  workflow_dispatch:

jobs:
  deploy-autotrader:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AUTOTRADER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AUTOTRADER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AUTOTRADER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push autotrader image
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./Dockerfile
          registryUrl: autotraderbinance.azurecr.io
          registryUsername: ${{ secrets.AUTOTRADER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AUTOTRADER_REGISTRY_PASSWORD }}
          containerAppName: autotrader
          resourceGroup: autotrader
          imageToBuild: autotraderbinance.azurecr.io/autotrader:${{ github.sha }}

  deploy-relay:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AUTOTRADER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AUTOTRADER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AUTOTRADER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push relay image
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./infra/Dockerfile.relay
          registryUrl: llmautotraderacr.azurecr.io
          registryUsername: ${{ secrets.LLMAUTOTRADER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LLMAUTOTRADER_REGISTRY_PASSWORD }}
          containerAppName: llmautotrader-relay
          resourceGroup: llmautotrader
          imageToBuild: llmautotraderacr.azurecr.io/llmautotrader-relay:${{ github.sha }}
