name: Trigger auto deployment for llmtrader-runner

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/llmtrader-runner-AutoDeployTrigger-fce05b31-a5b9-45c7-af61-c1fa39994159.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.LLMTRADERRUNNER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LLMTRADERRUNNER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LLMTRADERRUNNER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}infra/Dockerfile.runner
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: autotraderbinance.azurecr.io
          registryUsername: ${{ secrets.LLMTRADERRUNNER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LLMTRADERRUNNER_REGISTRY_PASSWORD }}
          containerAppName: llmtrader-runner
          resourceGroup: autotrader
          imageToBuild: autotraderbinance.azurecr.io/llmtrader-runner:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


